package com.mb2.merchant.payments.gateway.service.client.testconstants.merchant;

public class CbdcMerchantRegistrationJsons {
	public static final String apiRequest = "{\n"
			+ "    \"aggregator\": {\n"
			+ "        \"aggregatorId\": \"JARVISAGR4\",\n"
			+ "        \"aggregatorCode\": \"JARVISAGR4\"\n"
			+ "    },\n"
			+ "    \"merchant\": {\n"
			+ "        \"merchantId\": \"SetuDevonboard1\",\n"
			+ "        \"merchantName\": \"Dev\",\n"
			+ "        \"merchantMobile\": \"919050205871\",\n"
			+ "        \"mccCode\": \"5499\",\n"
			+ "        \"merchantEmail\": \"MHPL.PRANIT@GMAIL.COM\",\n"
			+ "        \"merchantType\": \"SMALL\",\n"
			+ "        \"ownershipType\": \"\"\n"
			+ "    },\n"
			+ "    \"paymentMethod\": \"CBDC\",\n"
			+ "    \"address\": {\n"
			+ "        \"city\": \"Bangalore\",\n"
			+ "        \"stateCode\": \"KA\",\n"
			+ "        \"pincode\": \"560001\",\n"
			+ "        \"fullAddress\": \"Bangalore\"\n"
			+ "    },\n"
			+ "    \"account\": {\n"
			+ "        \"ifsc\": \"KKBK0000958\",\n"
			+ "        \"poolAccount\": \"06432030000363\",\n"
			+ "        \"accountHolderName\": \"\",\n"
			+ "        \"accountRefNumber\": \"\",\n"
			+ "        \"accountType\": \"\"\n"
			+ "    },\n"
			+ "    \"additionalAttributes\": {\n"
			+ "        \"purpose\": \"Onboarding\",\n"
			+ "        \"ncifCheckFlag\": \"N\",\n"
			+ "        \"brand\": \"\",\n"
			+ "        \"callbackUrl\": \"\",\n"
			+ "        \"franchise\": \"\",\n"
			+ "        \"legal\": \"\",\n"
			+ "        \"storeIdentifier\": \"\",\n"
			+ "        \"terminalIdentifier\": \"1301216A\"\n"
			+ "    }\n"
			+ "}";

	public static final String oliveRequest = "{\n"
			+ "    \"address\": \"Bangalore\",\n"
			+ "    \"aggcode\": \"JARVISAGR4\",\n"
			+ "    \"ifsccode\": \"KKBK0000958\",\n"
			+ "    \"mcccode\": \"5499\",\n"
			+ "    \"mid\": \"SetuDevonboard1\",\n"
			+ "    \"mobnumber\": \"919050205871\",\n"
			+ "    \"merchname\": \"Dev\",\n"
			+ "    \"pincode\": \"560001\",\n"
			+ "    \"city\": \"Bangalore\",\n"
			+ "    \"state\": \"KA\",\n"
			+ "    \"terminalIdentifier\": \"1301216A\",\n"
			+ "    \"merchEmail\": \"MHPL.PRANIT@GMAIL.COM\",\n"
			+ "    \"merchtype\": \"SMALL\",\n"
			+ "    \"ownershiptype\": \"\",\n"
			+ "    \"storeIdentifier\": \"\",\n"
			+ "    \"franchise\": \"\",\n"
			+ "    \"brand\": \"\",\n"
			+ "    \"legal\": \"\",\n"
			+ "    \"accNum\": \"\",\n"
			+ "    \"callbackUrl\": \"\",\n"
			+ "    \"merchantOnboardingtype\": \"BANK\"\n"
			+ "}";
	
	public static final String oliveResponse = "{\n"
			+ "    \"code\": \"00\",\n"
			+ "    \"result\": \"SUCCESS\",\n"
			+ "    \"data\": \"SetuDevonboard1\"\n"
			+ "}";
	public static final String apiResponse = "{\n"
			+ "    \"responseCode\": \"00\",\n"
			+ "    \"responseMessage\": \"SUCCESS\",\n"
			+ "    \"data\": {\n"
			+ "        \"name\": \"SetuDevonboard1\"\n"
			+ "    }\n"
			+ "}";
}
